### ISSUE TITLE
Error when running cmake

### ISSUE THREAD

**Issue by dlradke** [tudelft3d/masbcpp#26]
I am hoping to use this package to process some lidar data for my Master's thesis. So far I am attemping to run cmake ., but I am getting the following error:

dlradke@III masbcpp % cmake .
-- Eigen found (include: /opt/local/include/eigen3, version: 3.3.7)
-- Checking for module 'flann'
--   No package 'flann' found
-- FLANN found (include: /opt/local/include, lib: optimized;/opt/local/lib/libflann_cpp.dylib;debug;/usr/local/Cellar/flann/1.9.1_7/lib/libflann_cpp.dylib)
-- Checking for module 'flann'
--   No package 'flann' found
-- FLANN found (include: /opt/local/include, lib: optimized;/opt/local/lib/libflann_cpp.dylib;debug;/usr/local/Cellar/flann/1.9.1_7/lib/libflann_cpp.dylib)
-- Checking for module 'flann'
--   No package 'flann' found
-- FLANN found (include: /opt/local/include, lib: optimized;/opt/local/lib/libflann_cpp.dylib;debug;/usr/local/Cellar/flann/1.9.1_7/lib/libflann_cpp.dylib)
-- looking for PCL_COMMON
-- looking for PCL_KDTREE
-- looking for PCL_OCTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_2D
-- looking for PCL_FEATURES
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dlradke/Desktop/masbcpp

It seems like the issue is with the 'flann' package. I installed flann-1.9.1_7 using Homebrew. I am running macOS Catalina 10.15.1. I also installed PCL version 1.9.1_4 using Homebrew. Any idea what the issue could be?

Cheers,
Dan

**Comment by dlradke** [comment]
Just want to close this. Instead of cloning the repostitory, I instead downloaded the source code from the release tab, and it compiled with no error.

**Comment by Ylannl** [comment]
Sorry I did not reply sooner. Glad you were able to compile the code now. Another option is to compile the kdtree2 branch, it does not depend on PCL.

**Comment by dlradke** [comment]
Thanks. I see now that it has been committed to most recently. I may try it out in the future.
